SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[ThisServer_All_ServerConfigurations] 
AS 
SELECT TOP 100 PERCENT	
		[server_name]
		, [access check cache bucket count]
		, [access check cache quota]
		, [Ad Hoc Distributed Queries]
		, [affinity I/O mask]
		, [affinity mask]
		, [affinity64 I/O mask]
		, [affinity64 mask]
		, [Agent XPs]
		, [allow updates]
		, [awe enabled]
		, [backup checksum default]
		, [backup compression default]
		, [blocked process threshold (s)]
		, [c2 audit mode]
		, [clr enabled]
		, [common criteria compliance enabled]
		, [contained database authentication]
		, [cost threshold for parallelism]
		, [cross db ownership chaining]
		, [cursor threshold]
		, [Database Mail XPs]
		, [default full-text language]
		, [default language]
		, [default trace enabled]
		, [disallow results from triggers]
		, [EKM provider enabled]
		, [filestream access level]
		, [fill factor (%)]
		, [ft crawl bandwidth (max)]
		, [ft crawl bandwidth (min)]
		, [ft notify bandwidth (max)]
		, [ft notify bandwidth (min)]
		, [index create memory (KB)]
		, [in-doubt xact resolution]
		, [lightweight pooling]
		, [locks]
		, [max degree of parallelism]
		, [max full-text crawl range]
		, [max server memory (MB)]
		, [max text repl size (B)]
		, [max worker threads]
		, [media retention]
		, [min memory per query (KB)]
		, [min server memory (MB)]
		, [nested triggers]
		, [network packet size (B)]
		, [Ole Automation Procedures]
		, [open objects]
		, [optimize for ad hoc workloads]
		, [PH timeout (s)]
		, [precompute rank]
		, [priority boost]
		, [query governor cost limit]
		, [query wait (s)]
		, [recovery interval (min)]
		, [remote access]
		, [remote admin connections]
		, [remote login timeout (s)]
		, [remote proc trans]
		, [remote query timeout (s)]
		, [Replication XPs]
		, [scan for startup procs]
		, [server trigger recursion]
		, [set working set size]
		, [show advanced options]
		, [SMO and DMO XPs]
		, [SQL Mail XPs]
		, [transform noise words]
		, [two digit year cutoff]
		, [user connections]
		, [user options]
		, [xp_cmdshell]
		, [BackupRootPath]
		, [LogFilesRootPath]
		, [KeepNBackups]
		, [DataCollectionTime]
	FROM [DBA].[dbo].[ServerConfigurations]
	WHERE server_name = @@SERVERNAME

UNION

SELECT [server_name]
		, [access check cache bucket count]
		, [access check cache quota]
		, [Ad Hoc Distributed Queries]
		, [affinity I/O mask]
		, [affinity mask]
		, [affinity64 I/O mask]
		, [affinity64 mask]
		, [Agent XPs]
		, [allow updates]
		, [awe enabled]
		, [backup checksum default]
		, [backup compression default]
		, [blocked process threshold (s)]
		, [c2 audit mode]
		, [clr enabled]
		, [common criteria compliance enabled]
		, [contained database authentication]
		, [cost threshold for parallelism]
		, [cross db ownership chaining]
		, [cursor threshold]
		, [Database Mail XPs]
		, [default full-text language]
		, [default language]
		, [default trace enabled]
		, [disallow results from triggers]
		, [EKM provider enabled]
		, [filestream access level]
		, [fill factor (%)]
		, [ft crawl bandwidth (max)]
		, [ft crawl bandwidth (min)]
		, [ft notify bandwidth (max)]
		, [ft notify bandwidth (min)]
		, [index create memory (KB)]
		, [in-doubt xact resolution]
		, [lightweight pooling]
		, [locks]
		, [max degree of parallelism]
		, [max full-text crawl range]
		, [max server memory (MB)]
		, [max text repl size (B)]
		, [max worker threads]
		, [media retention]
		, [min memory per query (KB)]
		, [min server memory (MB)]
		, [nested triggers]
		, [network packet size (B)]
		, [Ole Automation Procedures]
		, [open objects]
		, [optimize for ad hoc workloads]
		, [PH timeout (s)]
		, [precompute rank]
		, [priority boost]
		, [query governor cost limit]
		, [query wait (s)]
		, [recovery interval (min)]
		, [remote access]
		, [remote admin connections]
		, [remote login timeout (s)]
		, [remote proc trans]
		, [remote query timeout (s)]
		, [Replication XPs]
		, [scan for startup procs]
		, [server trigger recursion]
		, [set working set size]
		, [show advanced options]
		, [SMO and DMO XPs]
		, [SQL Mail XPs]
		, [transform noise words]
		, [two digit year cutoff]
		, [user connections]
		, [user options]
		, [xp_cmdshell]
		, [BackupRootPath]
		, [LogFilesRootPath]
		, [KeepNBackups]
		, [DataCollectionTime]
	FROM [DBA].[dbo].[ServerConfigurations_History]
	WHERE server_name = @@SERVERNAME
GO
