CREATE TABLE [dbo].[ServerConfigurations_History]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Action] [sys].[sysname] NOT NULL,
[server_name] [sys].[sysname] NOT NULL,
[access check cache bucket count] [sql_variant] NULL,
[access check cache quota] [sql_variant] NULL,
[Ad Hoc Distributed Queries] [sql_variant] NULL,
[affinity I/O mask] [sql_variant] NULL,
[affinity mask] [sql_variant] NULL,
[affinity64 I/O mask] [sql_variant] NULL,
[affinity64 mask] [sql_variant] NULL,
[Agent XPs] [sql_variant] NULL,
[allow updates] [sql_variant] NULL,
[awe enabled] [sql_variant] NULL,
[backup checksum default] [sql_variant] NULL,
[backup compression default] [sql_variant] NULL,
[blocked process threshold (s)] [sql_variant] NULL,
[c2 audit mode] [sql_variant] NULL,
[clr enabled] [sql_variant] NULL,
[common criteria compliance enabled] [sql_variant] NULL,
[contained database authentication] [sql_variant] NULL,
[cost threshold for parallelism] [sql_variant] NULL,
[cross db ownership chaining] [sql_variant] NULL,
[cursor threshold] [sql_variant] NULL,
[Database Mail XPs] [sql_variant] NULL,
[default full-text language] [sql_variant] NULL,
[default language] [sql_variant] NULL,
[default trace enabled] [sql_variant] NULL,
[disallow results from triggers] [sql_variant] NULL,
[EKM provider enabled] [sql_variant] NULL,
[filestream access level] [sql_variant] NULL,
[fill factor (%)] [sql_variant] NULL,
[ft crawl bandwidth (max)] [sql_variant] NULL,
[ft crawl bandwidth (min)] [sql_variant] NULL,
[ft notify bandwidth (max)] [sql_variant] NULL,
[ft notify bandwidth (min)] [sql_variant] NULL,
[index create memory (KB)] [sql_variant] NULL,
[in-doubt xact resolution] [sql_variant] NULL,
[lightweight pooling] [sql_variant] NULL,
[locks] [sql_variant] NULL,
[max degree of parallelism] [sql_variant] NULL,
[max full-text crawl range] [sql_variant] NULL,
[max server memory (MB)] [sql_variant] NULL,
[max text repl size (B)] [sql_variant] NULL,
[max worker threads] [sql_variant] NULL,
[media retention] [sql_variant] NULL,
[min memory per query (KB)] [sql_variant] NULL,
[min server memory (MB)] [sql_variant] NULL,
[nested triggers] [sql_variant] NULL,
[network packet size (B)] [sql_variant] NULL,
[Ole Automation Procedures] [sql_variant] NULL,
[open objects] [sql_variant] NULL,
[optimize for ad hoc workloads] [sql_variant] NULL,
[PH timeout (s)] [sql_variant] NULL,
[precompute rank] [sql_variant] NULL,
[priority boost] [sql_variant] NULL,
[query governor cost limit] [sql_variant] NULL,
[query wait (s)] [sql_variant] NULL,
[recovery interval (min)] [sql_variant] NULL,
[remote access] [sql_variant] NULL,
[remote admin connections] [sql_variant] NULL,
[remote login timeout (s)] [sql_variant] NULL,
[remote proc trans] [sql_variant] NULL,
[remote query timeout (s)] [sql_variant] NULL,
[Replication XPs] [sql_variant] NULL,
[scan for startup procs] [sql_variant] NULL,
[server trigger recursion] [sql_variant] NULL,
[set working set size] [sql_variant] NULL,
[show advanced options] [sql_variant] NULL,
[SMO and DMO XPs] [sql_variant] NULL,
[SQL Mail XPs] [sql_variant] NULL,
[transform noise words] [sql_variant] NULL,
[two digit year cutoff] [sql_variant] NULL,
[user connections] [sql_variant] NULL,
[user options] [sql_variant] NULL,
[xp_cmdshell] [sql_variant] NULL,
[trace_flags_enabled] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[BackupRootPath] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[LogFilesRootPath] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[KeepNBackups] [tinyint] NULL,
[DataCollectionTime] [datetime] NULL,
[RowCheckSum] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ServerConfigurations_History] ADD CONSTRAINT [PK_ServerConfigurations_History] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
