CREATE TABLE [dbo].[ServerConfigurations]
(
[ID] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[server_name] [sys].[sysname] NOT NULL,
[access check cache bucket count] [sql_variant] NULL,
[access check cache quota] [sql_variant] NULL,
[Ad Hoc Distributed Queries] [sql_variant] NULL,
[affinity I/O mask] [sql_variant] NULL,
[affinity mask] [sql_variant] NULL,
[affinity64 I/O mask] [sql_variant] NULL,
[affinity64 mask] [sql_variant] NULL,
[Agent XPs] [sql_variant] NULL,
[allow updates] [sql_variant] NULL,
[awe enabled] [sql_variant] NULL,
[backup checksum default] [sql_variant] NULL,
[backup compression default] [sql_variant] NULL,
[blocked process threshold (s)] [sql_variant] NULL,
[c2 audit mode] [sql_variant] NULL,
[clr enabled] [sql_variant] NULL,
[common criteria compliance enabled] [sql_variant] NULL,
[contained database authentication] [sql_variant] NULL,
[cost threshold for parallelism] [sql_variant] NULL,
[cross db ownership chaining] [sql_variant] NULL,
[cursor threshold] [sql_variant] NULL,
[Database Mail XPs] [sql_variant] NULL,
[default full-text language] [sql_variant] NULL,
[default language] [sql_variant] NULL,
[default trace enabled] [sql_variant] NULL,
[disallow results from triggers] [sql_variant] NULL,
[EKM provider enabled] [sql_variant] NULL,
[filestream access level] [sql_variant] NULL,
[fill factor (%)] [sql_variant] NULL,
[ft crawl bandwidth (max)] [sql_variant] NULL,
[ft crawl bandwidth (min)] [sql_variant] NULL,
[ft notify bandwidth (max)] [sql_variant] NULL,
[ft notify bandwidth (min)] [sql_variant] NULL,
[index create memory (KB)] [sql_variant] NULL,
[in-doubt xact resolution] [sql_variant] NULL,
[lightweight pooling] [sql_variant] NULL,
[locks] [sql_variant] NULL,
[max degree of parallelism] [sql_variant] NULL,
[max full-text crawl range] [sql_variant] NULL,
[max server memory (MB)] [sql_variant] NULL,
[max text repl size (B)] [sql_variant] NULL,
[max worker threads] [sql_variant] NULL,
[media retention] [sql_variant] NULL,
[min memory per query (KB)] [sql_variant] NULL,
[min server memory (MB)] [sql_variant] NULL,
[nested triggers] [sql_variant] NULL,
[network packet size (B)] [sql_variant] NULL,
[Ole Automation Procedures] [sql_variant] NULL,
[open objects] [sql_variant] NULL,
[optimize for ad hoc workloads] [sql_variant] NULL,
[PH timeout (s)] [sql_variant] NULL,
[precompute rank] [sql_variant] NULL,
[priority boost] [sql_variant] NULL,
[query governor cost limit] [sql_variant] NULL,
[query wait (s)] [sql_variant] NULL,
[recovery interval (min)] [sql_variant] NULL,
[remote access] [sql_variant] NULL,
[remote admin connections] [sql_variant] NULL,
[remote login timeout (s)] [sql_variant] NULL,
[remote proc trans] [sql_variant] NULL,
[remote query timeout (s)] [sql_variant] NULL,
[Replication XPs] [sql_variant] NULL,
[scan for startup procs] [sql_variant] NULL,
[server trigger recursion] [sql_variant] NULL,
[set working set size] [sql_variant] NULL,
[show advanced options] [sql_variant] NULL,
[SMO and DMO XPs] [sql_variant] NULL,
[SQL Mail XPs] [sql_variant] NULL,
[transform noise words] [sql_variant] NULL,
[two digit year cutoff] [sql_variant] NULL,
[user connections] [sql_variant] NULL,
[user options] [sql_variant] NULL,
[xp_cmdshell] [sql_variant] NULL,
[trace_flags_enabled] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[BackupRootPath] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[LogFilesRootPath] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[KeepNBackups] [tinyint] NULL CONSTRAINT [DF_InstanceConfigurations_KeepNBackups] DEFAULT ((10)),
[DataCollectionTime] [datetime] NULL,
[RowCheckSum] AS (checksum([server_name],[access check cache bucket count],[access check cache quota],[Ad Hoc Distributed Queries],[affinity I/O mask],[affinity mask],[affinity64 I/O mask],[affinity64 mask],[Agent XPs],[allow updates],[awe enabled],[backup checksum default],[backup compression default],[blocked process threshold (s)],[c2 audit mode],[clr enabled],[common criteria compliance enabled],[contained database authentication],[cost threshold for parallelism],[cross db ownership chaining],[cursor threshold],[Database Mail XPs],[default full-text language],[default language],[default trace enabled],[disallow results from triggers],[EKM provider enabled],[filestream access level],[fill factor (%)],[ft crawl bandwidth (max)],[ft crawl bandwidth (min)],[ft notify bandwidth (max)],[ft notify bandwidth (min)],[index create memory (KB)],[in-doubt xact resolution],[lightweight pooling],[locks],[max degree of parallelism],[max full-text crawl range],[max server memory (MB)],[max text repl size (B)],[max worker threads],[media retention],[min memory per query (KB)],[min server memory (MB)],[nested triggers],[network packet size (B)],[Ole Automation Procedures],[open objects],[optimize for ad hoc workloads],[PH timeout (s)],[precompute rank],[priority boost],[query governor cost limit],[query wait (s)],[recovery interval (min)],[remote access],[remote admin connections],[remote login timeout (s)],[remote proc trans],[remote query timeout (s)],[Replication XPs],[scan for startup procs],[server trigger recursion],[set working set size],[show advanced options],[SMO and DMO XPs],[SQL Mail XPs],[transform noise words],[two digit year cutoff],[user connections],[user options],[xp_cmdshell],[trace_flags_enabled],[BackupRootPath],[LogFilesRootPath],[KeepNBackups]))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ServerConfigurations] ADD CONSTRAINT [PK_ServerConfigurations] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UIX_ServerConfigurations_server_name] ON [dbo].[ServerConfigurations] ([server_name]) ON [PRIMARY]
GO
